shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('greetings/', views.greetings),
    path('shop/', views.list_item),
    path('shop/<int:item_id>/', views.detail_item, name='detail_item'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls'))
]

shop/models.py
from django.db import models

# Create your models here.


class Item(models.Model):
    name = models.CharField(max_length=30, default='')
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f'{self.name}-{self.price}'


class Purchase(models.Model):
    name = models.CharField(max_length=30, default='')
    age = models.IntegerField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    date_purchase = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'

    def __str__(self):
        return f'{self.name}-{self.age}-{self.item.name}{self.item.price}'

shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Item, Purchase




def greetings(request):
    return HttpResponse("Добро пожаловать в наш магазин")


def list_item(request):
    items = Item.objects.all()
    context = {
        'items': items
    }
    return render(request, 'list_item.html', context)


def detail_item(request, item_id):
    item = Item.objects.get(id=item_id)
    context = {
        'item': item
    }
    return render(request, 'detail_item.html', context)

shop/templates/base.html
<!doctype html>
<html lang="ar" dir="rtl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.rtl.min.css" integrity="sha384-T5m5WERuXcjgzF8DAb7tRkByEZQGcpraRTinjpywg37AO96WoYN9+hrhDVoM6CaT" crossorigin="anonymous">
  </head>
  <body>
  <div class="container md-5 mt-5">
    {% block content %}
    {% endblock content%}

  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>


  </body>
</html>

shop/templates/detail_item.html
{% extends 'base.html'%}
{% block content %}
<form method="POST">
  {{ item.name }}
  <ol>
    {% for purchase in item.purchase_set.all %}
    <li>{{ purchase.name }}-{{purchase.age}}-{{purchase.item}}-{{purchase.date_purchase}}</li>
    {%endfor%}
</ol>
</form>
{% endblock content%}

shop/templates/list_item.html
{% extends 'base.html'%}

{% block content %}
<ul>
    {% for item in items %}
    <li> <a href="{% url 'detail_item' item.id %}">{{ item.name }}-{{item.price}}</a></li>
    {%endfor%}
</ul>


{% endblock content%}